type side = "top" | "top-right" | "bottom-right" | "bottom" | "bottom-left" | "top-left"

type upgradeRequirement = {
	currency:string,
	amount:number,
}

type upgrades = {
	id:string,
	name:string,
	description:string,
	side:side,
	parentId:string,
	requireId:{string},
	visibleWhen: {string}?,
	requirements:{upgradeRequirement},
	upgradeIcon :string?,
	hexColor:string,
	isPortal:boolean?,
	portalTo:string?,
	toggleButton:boolean?,

}

type upgradeTreeData = {
	hexRadius:number,
	panLimit:Vector2,
	hexImg:{string},
	upgradeIcon:{string},
	currencyIcon:{string},
	upgrades:{[string]:{upgrades}},
}

local settings = require(script.Parent.upgradeTreeSettings)

local upgradeTreeData:upgradeTreeData = {
	hexRadius = settings.hexRadius,
	panLimit = settings.panLimit,
	
	hexImg = settings.hexImg,
	
	upgradeIcon = settings.upgradeIcon,
	
	currencyIcon = settings.currencyIcon,
	
	upgrades = {
		mainTree = {
			{
				id = "exit",
				name = "",
				description = nil,
				side = "top",
				parentId = nil,
				requireId = {},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "x",
				hexImg = "red",
				toggleButton = true,
			},
			{
				id = "Eggs I",
				name = "Eggs I",
				description = "Lets You Roll 1 Egg!",
				side = "top-left",
				parentId = "exit",
				requireId = {},
				requirements = {{ currency = "coins", amount = 15 }},
				upgradeIcon = "oneEgg",
				hexImg = "blue",
			},
			{
				id = "Eggs II",
				name = "Eggs II",
				description = "Lets You Roll 2 Eggs!",
				side = "top-left",
				parentId = "Eggs I",
				requireId = {"Eggs I"},
				requirements = {{ currency = "coins", amount = 2500 }},
				upgradeIcon = "twoEggs",
				hexImg = "blue",
			},
			{
				id = "Eggs III",
				name = "Eggs III",
				description = "Lets You Roll 3 Eggs!",
				side = "bottom-left",
				parentId = "Eggs II",
				requireId = {"Eggs II"},
				requirements = {{ currency = "coins", amount = 5000000 }},
				upgradeIcon = "threeEggs",
				hexImg = "blue",
			},
			{
				id = "Eggs IV",
				name = "Eggs IV",
				description = "Lets You Roll 4 Eggs!",
				side = "top-left",
				parentId = "Eggs III",
				requireId = {"Eggs III"},
				requirements = {{ currency = "coins", amount = 1002000000 }},
				upgradeIcon = "fourEggs",
				hexImg = "blue",
			},
			{
				id = "Eggs V",
				name = "Eggs V",
				description = "Lets You Roll 5 Eggs!",
				side = "bottom-left",
				parentId = "Eggs IV",
				requireId = {"Eggs IV"},
				requirements = {{ currency = "coins", amount = 1555000000000 }},
				upgradeIcon = "fiveEggs",
				hexImg = "blue",
			},
			-- speed branch
			{
				id = "eggSpeed I",
				name = "Roll Speed I",
				description = "Roll 10% Faster!",
				side = "top-right",
				parentId = "Eggs I",
				requireId = {"Eggs I"},
				requirements = {{ currency = "coins", amount = 500 }},
				upgradeIcon = "lightning",
				hexImg = "blue",
			},
			{
				id = "eggSpeed II",
				name = "Roll Speed II",
				description = "Roll 25% Faster!",
				side = "bottom-right",
				parentId = "eggSpeed I",
				requireId = {"eggSpeed I"},
				requirements = {{ currency = "coins", amount = 10000 }},
				upgradeIcon = "lightning",
				hexImg = "blue",
			},
			{
				id = "eggSpeed III",
				name = "Roll Speed III",
				description = "Roll 50% Faster!",
				side = "top-right",
				parentId = "eggSpeed II",
				requireId = {"eggSpeed II"},
				requirements = {{ currency = "coins", amount = 500000 }},
				upgradeIcon = "lightning",
				hexImg = "blue",
			},
			-- luck branch
			{
				id = "luck I",
				name = "Luck I",
				description = "+5% Rare Chance!",
				side = "bottom-right",
				parentId = "exit",
				requireId = {},
				requirements = {{ currency = "coins", amount = 100 }},
				upgradeIcon = "clover",
				hexImg = "blue",
			},
			{
				id = "luck II",
				name = "Luck II",
				description = "+10% Rare Chance!",
				side = "bottom-right",
				parentId = "luck I",
				requireId = {"luck I"},
				requirements = {{ currency = "coins", amount = 5000 }},
				upgradeIcon = "clover",
				hexImg = "blue",
			},
			{
				id = "luck III",
				name = "Luck III",
				description = "+20% Rare Chance!",
				side = "bottom-right",
				parentId = "luck II",
				requireId = {"luck II"},
				requirements = {{ currency = "coins", amount = 250000 }},
				upgradeIcon = "purpleClover",
				hexImg = "blue",
			},
			{
				id = "luck IV",
				name = "Luck IV",
				description = "+35% Rare Chance!",
				side = "bottom",
				parentId = "luck III",
				requireId = {"luck III"},
				requirements = {{ currency = "coins", amount = 10000000 }},
				upgradeIcon = "purpleClover",
				hexImg = "blue",
			},
			-- coin branch
			{
				id = "coins I",
				name = "Coins I",
				description = "+10% Coin Gain!",
				side = "bottom-left",
				parentId = "exit",
				requireId = {},
				requirements = {{ currency = "coins", amount = 50 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coins II",
				name = "Coins II",
				description = "+25% Coin Gain!",
				side = "bottom-left",
				parentId = "coins I",
				requireId = {"coins I"},
				requirements = {{ currency = "coins", amount = 2000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coins III",
				name = "Coins III",
				description = "+50% Coin Gain!",
				side = "bottom",
				parentId = "coins II",
				requireId = {"coins II"},
				requirements = {{ currency = "coins", amount = 100000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coins IV",
				name = "Coins IV",
				description = "Double Coin Gain!",
				side = "bottom-left",
				parentId = "coins III",
				requireId = {"coins III"},
				requirements = {{ currency = "coins", amount = 5000000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coins V",
				name = "Coins V",
				description = "Triple Coin Gain!",
				side = "bottom",
				parentId = "coins IV",
				requireId = {"coins IV"},
				requirements = {{ currency = "coins", amount = 500000000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			-- portals
			{
				id = "playerPortal",
				name = "Player",
				description = nil,
				side = "top-right",
				parentId = "Eggs II",
				requireId = {"Eggs II", "eggSpeed I"},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "player",
				hexImg = "gold",
				isPortal = true,
				portalTo = "playerTree",
			},
			{
				id = "luckPortal",
				name = "Lucky Shop",
				description = nil,
				side = "bottom-left",
				parentId = "luck III",
				requireId = {"luck III", "luck IV"},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "purpleClover",
				hexImg = "gold",
				isPortal = true,
				portalTo = "luckTree",
			},
			{
				id = "coinPortal",
				name = "Coin Shop",
				description = nil,
				side = "bottom-right",
				parentId = "coins IV",
				requireId = {"coins IV", "coins III"},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "coin",
				hexImg = "gold",
				isPortal = true,
				portalTo = "coinTree",
			},
		} :: {upgrades},

		playerTree = {
			{
				id = "playerBack",
				name = "",
				description = nil,
				side = "top",
				parentId = nil,
				requireId = {},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "house",
				hexImg = "red",
				isPortal = true,
				portalTo = "mainTree",
			},
			{
				id = "friends1",
				name = "Friends I",
				description = "+1% Currency per Friend in Server!",
				side = "top-right",
				parentId = "playerBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 1000 }},
				upgradeIcon = "friends",
				hexImg = "blue",
			},
			{
				id = "friends2",
				name = "Friends II",
				description = "+3% Currency per Friend in Server!",
				side = "bottom-right",
				parentId = "friends1",
				requireId = {"friends1"},
				requirements = {{ currency = "coins", amount = 25000 }},
				upgradeIcon = "friends",
				hexImg = "blue",
			},
			{
				id = "friends3",
				name = "Friends III",
				description = "+5% Currency per Friend in Server!",
				side = "top-right",
				parentId = "friends2",
				requireId = {"friends2"},
				requirements = {{ currency = "coins", amount = 500000 }},
				upgradeIcon = "friends",
				hexImg = "blue",
			},
			{
				id = "playtime1",
				name = "Playtime I",
				description = "+5% Coins per Hour Played!",
				side = "top-left",
				parentId = "playerBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 500 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "playtime2",
				name = "Playtime II",
				description = "+15% Coins per Hour Played!",
				side = "top-left",
				parentId = "playtime1",
				requireId = {"playtime1"},
				requirements = {{ currency = "coins", amount = 15000 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "playtime3",
				name = "Playtime III",
				description = "+30% Coins per Hour Played!",
				side = "bottom-left",
				parentId = "playtime2",
				requireId = {"playtime2"},
				requirements = {{ currency = "coins", amount = 250000 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "streak1",
				name = "Streak I",
				description = "+10% Coins for Daily Streak!",
				side = "bottom-right",
				parentId = "playerBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 750 }},
				upgradeIcon = "star",
				hexImg = "blue",
			},
			{
				id = "streak2",
				name = "Streak II",
				description = "+25% Coins for Daily Streak!",
				side = "bottom-right",
				parentId = "streak1",
				requireId = {"streak1"},
				requirements = {{ currency = "coins", amount = 20000 }},
				upgradeIcon = "star",
				hexImg = "blue",
			},
			{
				id = "streak3",
				name = "Streak III",
				description = "+50% Coins for Daily Streak!",
				side = "bottom",
				parentId = "streak2",
				requireId = {"streak2"},
				requirements = {{ currency = "coins", amount = 400000 }},
				upgradeIcon = "star",
				hexImg = "blue",
			},
			{
				id = "vip1",
				name = "VIP I",
				description = "+20% All Gains as VIP!",
				side = "bottom-left",
				parentId = "playerBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 5000 }},
				upgradeIcon = "crown",
				hexImg = "blue",
			},
			{
				id = "vip2",
				name = "VIP II",
				description = "+50% All Gains as VIP!",
				side = "bottom-left",
				parentId = "vip1",
				requireId = {"vip1"},
				requirements = {{ currency = "coins", amount = 100000 }},
				upgradeIcon = "crown",
				hexImg = "blue",
			},
			{
				id = "vip3",
				name = "VIP III",
				description = "x2 All Gains as VIP!",
				side = "bottom",
				parentId = "vip2",
				requireId = {"vip2"},
				requirements = {{ currency = "coins", amount = 2000000 }},
				upgradeIcon = "crown",
				hexImg = "blue",
			},
		} :: {upgrades},

		luckTree = {
			{
				id = "luckBack",
				name = "",
				description = nil,
				side = "top",
				parentId = nil,
				requireId = {},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "house",
				hexImg = "red",
				isPortal = true,
				portalTo = "mainTree",
			},
			{
				id = "epicLuck1",
				name = "Epic Luck I",
				description = "+5% Epic Egg Chance!",
				side = "top-left",
				parentId = "luckBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 50000 }},
				upgradeIcon = "clover",
				hexImg = "blue",
			},
			{
				id = "epicLuck2",
				name = "Epic Luck II",
				description = "+12% Epic Egg Chance!",
				side = "bottom-left",
				parentId = "epicLuck1",
				requireId = {"epicLuck1"},
				requirements = {{ currency = "coins", amount = 500000 }},
				upgradeIcon = "clover",
				hexImg = "blue",
			},
			{
				id = "epicLuck3",
				name = "Epic Luck III",
				description = "+25% Epic Egg Chance!",
				side = "top-left",
				parentId = "epicLuck2",
				requireId = {"epicLuck2"},
				requirements = {{ currency = "coins", amount = 5000000 }},
				upgradeIcon = "purpleClover",
				hexImg = "blue",
			},
			{
				id = "legendLuck1",
				name = "Legend Luck I",
				description = "+2% Legendary Egg Chance!",
				side = "bottom-right",
				parentId = "luckBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 200000 }},
				upgradeIcon = "purpleClover",
				hexImg = "blue",
			},
			{
				id = "legendLuck2",
				name = "Legend Luck II",
				description = "+5% Legendary Egg Chance!",
				side = "top-right",
				parentId = "legendLuck1",
				requireId = {"legendLuck1"},
				requirements = {{ currency = "coins", amount = 2000000 }},
				upgradeIcon = "purpleClover",
				hexImg = "blue",
			},
			{
				id = "legendLuck3",
				name = "Legend Luck III",
				description = "+10% Legendary Egg Chance!",
				side = "bottom-right",
				parentId = "legendLuck2",
				requireId = {"legendLuck2"},
				requirements = {{ currency = "coins", amount = 20000000 }},
				upgradeIcon = "purpleClover",
				hexImg = "blue",
			},
			{
				id = "rerollLuck1",
				name = "Reroll I",
				description = "1 Free Reroll per Day!",
				side = "bottom-left",
				parentId = "luckBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 100000 }},
				upgradeIcon = "dice",
				hexImg = "blue",
			},
			{
				id = "rerollLuck2",
				name = "Reroll II",
				description = "3 Free Rerolls per Day!",
				side = "bottom",
				parentId = "rerollLuck1",
				requireId = {"rerollLuck1"},
				requirements = {{ currency = "coins", amount = 1000000 }},
				upgradeIcon = "dice",
				hexImg = "blue",
			},
			{
				id = "rerollLuck3",
				name = "Reroll III",
				description = "Unlimited Free Rerolls!",
				side = "bottom-left",
				parentId = "rerollLuck2",
				requireId = {"rerollLuck2"},
				requirements = {{ currency = "coins", amount = 50000000 }},
				upgradeIcon = "goldDice",
				hexImg = "blue",
			},
		} :: {upgrades},

		coinTree = {
			{
				id = "coinBack",
				name = "",
				description = nil,
				side = "top",
				parentId = nil,
				requireId = {},
				requirements = {{ currency = "coins", amount = 0 }},
				upgradeIcon = "house",
				hexImg = "red",
				isPortal = true,
				portalTo = "mainTree",
			},
			{
				id = "coinMult1",
				name = "Multiplier I",
				description = "x1.5 Coin Multiplier!",
				side = "top-left",
				parentId = "coinBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 1000000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coinMult2",
				name = "Multiplier II",
				description = "x2 Coin Multiplier!",
				side = "bottom-left",
				parentId = "coinMult1",
				requireId = {"coinMult1"},
				requirements = {{ currency = "coins", amount = 10000000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coinMult3",
				name = "Multiplier III",
				description = "x3 Coin Multiplier!",
				side = "top-left",
				parentId = "coinMult2",
				requireId = {"coinMult2"},
				requirements = {{ currency = "coins", amount = 100000000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coinMult4",
				name = "Multiplier IV",
				description = "x5 Coin Multiplier!",
				side = "bottom-left",
				parentId = "coinMult3",
				requireId = {"coinMult3"},
				requirements = {{ currency = "coins", amount = 1000000000 }},
				upgradeIcon = "coin",
				hexImg = "blue",
			},
			{
				id = "coinPassive1",
				name = "Passive I",
				description = "+100 Coins per Minute!",
				side = "top-right",
				parentId = "coinBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 500000 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "coinPassive2",
				name = "Passive II",
				description = "+500 Coins per Minute!",
				side = "top-right",
				parentId = "coinPassive1",
				requireId = {"coinPassive1"},
				requirements = {{ currency = "coins", amount = 5000000 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "coinPassive3",
				name = "Passive III",
				description = "+2000 Coins per Minute!",
				side = "bottom-right",
				parentId = "coinPassive2",
				requireId = {"coinPassive2"},
				requirements = {{ currency = "coins", amount = 50000000 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "coinPassive4",
				name = "Passive IV",
				description = "+10000 Coins per Minute!",
				side = "top-right",
				parentId = "coinPassive3",
				requireId = {"coinPassive3"},
				requirements = {{ currency = "coins", amount = 500000000 }},
				upgradeIcon = "clock",
				hexImg = "blue",
			},
			{
				id = "coinBonus1",
				name = "Bonus I",
				description = "+50% Coins on First Roll of Day!",
				side = "bottom-right",
				parentId = "coinBack",
				requireId = {},
				requirements = {{ currency = "coins", amount = 750000 }},
				upgradeIcon = "star",
				hexImg = "blue",
			},
			{
				id = "coinBonus2",
				name = "Bonus II",
				description = "+100% Coins on First Roll of Day!",
				side = "bottom",
				parentId = "coinBonus1",
				requireId = {"coinBonus1"},
				requirements = {{ currency = "coins", amount = 7500000 }},
				upgradeIcon = "star",
				hexImg = "blue",
			},
			{
				id = "coinBonus3",
				name = "Bonus III",
				description = "+200% Coins on First Roll of Day!",
				side = "bottom-right",
				parentId = "coinBonus2",
				requireId = {"coinBonus2"},
				requirements = {{ currency = "coins", amount = 75000000 }},
				upgradeIcon = "star",
				hexImg = "blue",
			},
		} :: {upgrades},
	}
}

return upgradeTreeData
